ppc64/ppc64spec: skip build unless Go 1.8+ or amd64
Fix build failure:

../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:146: undefined: pdf.Outline
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:153: undefined: pdf.Outline
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:174: undefined: pdf.Page
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:271: undefined: pdf.Content
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:271: undefined: pdf.Text
../../gopath/src/golang.org/x/arch/ppc64/ppc64spec/spec.go:396: undefined: pdf.Rect

ppc64spec depends on other packages that don't build on 32-bit
systems prior to Go 1.8.

Fixes golang/go#17635
Updates golang/go#12840

Change-Id: I594adef1d0bc498940183215c7c5a958628a254a
Reviewed-on: https://go-review.googlesource.com/33247
Run-TryBot: Brad Fitzpatrick <bradfitz@golang.org>
TryBot-Result: Gobot Gobot <gobot@golang.org>
Reviewed-by: Ian Lance Taylor <iant@golang.org>