arm64/arm64spec: skip build on 386 targets
Fix build failure:

..\..\gopath\src\golang.org\x\arch\arm64\arm64spec\spec.go:137: undefined: pdf.Outline
..\..\gopath\src\golang.org\x\arch\arm64\arm64spec\spec.go:148: undefined: pdf.Outline
..\..\gopath\src\golang.org\x\arch\arm64\arm64spec\spec.go:167: undefined: pdf.Page
..\..\gopath\src\golang.org\x\arch\arm64\arm64spec\spec.go:167: undefined: pdf.Reader
..\..\gopath\src\golang.org\x\arch\arm64\arm64spec\spec.go:425: undefined: pdf.Content
..\..\gopath\src\golang.org\x\arch\arm64\arm64spec\spec.go:425: undefined: pdf.Text
..\..\gopath\src\golang.org\x\arch\arm64\arm64spec\spec.go:616: undefined: pdf.Rect

arm64spec depends on rsc.io/pdf which does not currently build on 386 platforms.

Updates golang/go#12840

Change-Id: I40de19c617f90bcf696586b57a4d09b1d307f0df
Reviewed-on: https://go-review.googlesource.com/49015
Reviewed-by: Brad Fitzpatrick <bradfitz@golang.org>
Run-TryBot: Brad Fitzpatrick <bradfitz@golang.org>
TryBot-Result: Gobot Gobot <gobot@golang.org>